Bump Flask.SocketIO version to 5.6.1
Needed because 5.6.0 is broken on Flask versions 3.1.2 and up (docassemble
is currently using 3.1.3).

An example of the errors that appear in websockets.log

```
  File "/usr/share/docassemble/local3.12/lib/python3.12/site-packages/flask_socketio/__init__.py", line 815, in _handle_event
    ctx.session = session_obj
    ^^^^^^^^^^^
AttributeError: property 'session' of 'RequestContext' object has no setter
```

Full description of what's fixed at https://github.com/miguelgrinberg/Flask-SocketIO/issues/2152.