Update commands to update docassemble core
* the `docassemble` package is no longer present, so it's not needed in the command.
* The `--no-index` command no longer works, and results in this error:
    ```
    ERROR: Could not find a version that satisfies the requirement setuptools==80.9.0 (from versions: none)
    ERROR: No matching distribution found for setuptools==80.9.0
    ```
    Running without it allows pip to find setuptools (not sure why it can't
   find it without the index, as it is installed already).